name: darpan_mine
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.17

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  custom_radio_grouped_button: any
  xml: 5.3.1
  language_picker: ^0.4.3
  responsive_framework: 0.1.9
  logger: 1.0.0
  timeline_tile: 2.0.0
  fluid_bottom_nav_bar: 1.3.0
  basic_utils: 3.0.0
  cupertino_icons: 1.0.4
  material_design_icons_flutter: 5.0.6595
  flutter_screenutil: 5.5.2
  intl: 0.17.0
  collapsible_sidebar: 2.0.1+2
  image_picker: 0.8.4+1
  http: 0.13.3
  printing: 5.7.2
  native_pdf_view: 5.0.0
  share_plus: 2.0.0
  enough_convert: ^1.6.0
  sqfentity: ^2.2.0+6
  sqfentity_gen: ^2.2.0+6
  flutter_keyboard_visibility: 5.0.0
  group_radio_button: 1.1.0
  flutter_neumorphic: 3.2.0
  fluttertoast: 8.0.9
  pdf: ^3.6.5
  dart_ipify: 1.1.1
  is_first_run: 1.0.0
  package_info_plus: 1.0.1
  android_alarm_manager_plus: 1.0.1
  syncfusion_flutter_pdf: 19.1.54-beta
  webview_flutter: 2.0.6
  flutter_file_manager: any
  file_manager: 1.0.0
  disk_space: 0.2.1
  http_server: any
  barcode_image : 2.0.1
  android_intent: 2.0.2
  dhttpd: 4.0.1
  device_info: 2.0.3
  dio: 4.0.4
  google_maps_flutter: 2.1.1
  geolocator: 7.0.0
  google_fonts: 2.2.0
  flutter_archive: 4.1.0
  signature: 5.0.0
  shared_preferences: 2.0.11
  sqflite: 2.0.1
  flutter_html_to_pdf: 0.7.0
  open_file: 3.2.1
  open_settings: 2.0.2
  badges: 2.0.2
  path_provider: 2.0.2
  internet_connection_checker: 0.0.1+3
  permission_handler: 6.0.0
  connectivity: 3.0.6
  double_back_to_close_app: 2.1.0
  barcode_widget: 2.0.2
  network_info_plus: 1.0.1
  flutter_beep: 1.0.0
  universal_html: 2.0.8
  flutter_windowmanager: 0.2.0
  sms_autofill: 2.2.0
  csv: 5.0.0
  expandable: 5.0.1
  convert: 3.0.0
  alt_sms_autofill: 1.0.0
  pin_code_fields: 7.4.0
  jwt_decoder: ^2.0.1
  root: ^2.0.2
  get: 4.6.5
  provider: ^6.0.4
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0
  quick_usb:
    path: ./quick_usb/
  rdservice:
    path: ./rdservice/
  android_bluetooth_printer:
    path: ./android_bluetooth_printer/
  qrcode:
    path: ./qrcode/
  scanner_plugin:
    path: ./scanner_plugin/
  ml_scanner_plugin:
    path: ./ml_scanner_plugin/
  zxing_scanner:
    path: ./zxing_scanner/
  share:
    path: ./share/
  data_connection_checker:
    path: ./data_connection_checker-0.3.4/
  imei_plugin:
    path: ./imei_plugin-1.2.0/

  age_calculator:
    path: ./age_calculator/
  qr_code_scanner:
    path: ./qr_code_scanner/
  newenc:
    path: ./newenc/
#  google_mlkit_translation:
#    path: ./google_mlkit_translation/

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.1.10
  build_verify: 3.0.0
  flutter_lints: 1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/PostOfficeDB.db
    - assets/web/
    - assets/certificate/
